(add-to-list 'load-path "~/.emacs.d/vendor")

(add-to-list 'load-path "~/.emacs.d/customizations")
(load "packages.el")
(load "utils.el")
(load "shell-integration.el")
(load "navigation.el")
(load "ui.el")
(load "editing.el")
(load "misc.el")
(load "lisp-editing.el")
(load "setup-clojure.el")
(load "setup-web.el")
(load "keyboard-macros.el")
