(defvar user-folder)
(defvar gk/prefix)
(defvar gk/implementation-folder)
(defvar gk/spec-folder)
(defvar gk/implementation-suffix)
(defvar gk/spec-suffix)
(setq user-folder "/Users/joshuag/")
(setq gk/prefix (concat user-folder "repos/" "GitKraken/"))
(setq gk/implementation-folder "src/js/")
(setq gk/spec-folder "spec/unitTests/")
(setq gk/implementation-suffix ".js")
(setq gk/spec-suffix "-spec.js")
