(load "navigation/setup-uniquify.el")
(load "navigation/setup-recentf.el")
(load "navigation/setup-ido.el")
(load "navigation/setup-smex.el")
(load "navigation/setup-projectile.el")
(load "navigation/switch-to-previous-buffer.el")
(load "navigation/toggle-between-implementation-and-spec.el")
(load "navigation/search.el")
